apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo-app
  template:
    metadata:
      labels:
        app: devops-demo-app
    spec:
      containers:
      - name: devops-demo-app
        image: arunkumar1611/devops-demo-app:6
        ports:
        - containerPort: 8080
