apiVersion: v1
kind: Service
metadata:
  name: devops-demo-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: devops-demo-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
